### PR TITLE
Allow scripting in replays

### PR DESCRIPTION
**Pull request by bratkartoff**

### CODE REVIEW

**Comment by maxmitti** [comment]
Why do you want this?
It is really easy to desync a replay with scripting.

**Comment by bratkartoff** [comment]
- Debugging, or in general getting more precise info about what happened (e. g. `/script FindObject(...)->Get...`)
- Watching a replay from a players perspective without FoW

About desyncing: I'm aware of that, but I think you should be fine if you avoid modifying the game state (and if you do, it's your own fault)

**Review by Fulgen301 — CHANGES_REQUESTED** [review]
It's relatively easy to script in replays to the point where a user might accidentally try out the fancy script command they found somewhere and brick the rest of the replay without knowing why.

@maxmitti had the idea of locking it behind a config value that is not exposed to the UI, that might be a good solution as the barrier to break the round is higher.

**Review by maxmitti — APPROVED** [review]
I have tried make the if easier to understand, as the other one was quite confusing for me.
Please check if the semantics are still correct.

Otherwise this PR looks good to me.

**Comment by bratkartoff** [comment]
I think the original intention was "only skip the check if `AllowScriptingInReplays = true` and `isReplay = true`, otherwise work like before", but the modified if statement is much easier to read.
The semantics are identical if you take into account that `isReplay = true` implies `iByClient != C4ClientIDHost`

**Pull request merged**
